In [2]:
%pip install yfinance

Requirement already satisfied: yfinance in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (1.5.1)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (6.33.2)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (2.2.6)
Requirement already satisfied: pytz>=2022.5 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: websockets>=13.0 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (16.1)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\ujjwa\appdata\roaming\python\python310\site-packages (from yfinance) (4.10.0)
Requirement already satisfied: requests>=2.31 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: peewee>=3.16.2 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (4.1.2)
Requirement already satisfied: pandas>=1.3.0 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: rich in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from curl_cffi>=0.15->yfinance) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->yfinance) (2.6.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: pycparser in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ujjwa\appdata\roaming\python\python310\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\ujjwa\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Yahoo Finance provides historical market data for:

Stocks
ETFs
Commodities
Forex
Indices
Cryptocurrencies

In [3]:
import pandas as pd
import numpy as np
import yfinance as yf
from pathlib import Path

Commodity Tickers
GC=F: Gold Futures
SI=F: Silver futures

Future: Imagine an agreement today:
"I will buy Gold next month for ₹7000."
That agreement itself is called a futures contract.

Since futures are actively traded every day, they provide a good representation of commodity prices.

In [4]:
COMMODITIES = {
    "Gold": "GC=F",
    "Silver": "SI=F",
    "Crude_Oil": "CL=F",
    "Natural_Gas": "NG=F",
    "Copper": "HG=F"
}

In [5]:
START_DATE = "2015-01-01"
END_DATE = None  # Downloads data up to today

In [6]:
RAW_DATA_PATH = Path("../data/raw")
RAW_DATA_PATH.mkdir(parents=True, exist_ok=True)

In [8]:

for commodity, ticker in COMMODITIES.items():

    print(f"Downloading {commodity}...")

    df = yf.download(
        ticker,
        start=START_DATE,
        auto_adjust=False,
        progress=False
    )

    # Flatten MultiIndex columns
    if hasattr(df.columns, "nlevels") and df.columns.nlevels > 1:
        df.columns = df.columns.get_level_values(0)

    # Reset index so Date becomes a normal column
    df.reset_index(inplace=True)

    # Save
    df.to_csv(RAW_DATA_PATH / f"{commodity.lower()}.csv", index=False)

print("Download Complete!")

Downloading Gold...
Downloading Silver...
Downloading Crude_Oil...
Downloading Natural_Gas...
Downloading Copper...
Download Complete!

In [28]:
gold=pd.read_csv("../data/raw/gold.csv")
silver=pd.read_csv("../data/raw/silver.csv")
copper=pd.read_csv("../data/raw/copper.csv")
crude_oil=pd.read_csv("../data/raw/crude_oil.csv")
natural_gas=pd.read_csv("../data/raw/natural_gas.csv")

In [10]:
gold.shape

(2895, 7)

In [11]:
gold.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2895 entries, 0 to 2894
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2895 non-null   object
 1   Adj Close  2895 non-null   float64
 2   Close      2895 non-null   float64
 3   High       2895 non-null   float64
 4   Low        2895 non-null   float64
 5   Open       2895 non-null   float64
 6   Volume     2895 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 158.4+ KB

In [20]:
gold["Date"]=pd.to_datetime(gold["Date"])

In [13]:
gold.isnull().sum()

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [14]:
gold.duplicated().sum()

np.int64(0)

In [15]:
print(gold["Date"].min())
print(gold["Date"].max())

2015-01-02 00:00:00
2026-07-10 00:00:00

In [16]:
gold.describe()

,Date,Adj Close,Close,High,Low,Open,Volume
count,2895,2895.000000,2895.000000,2895.000000,2895.000000,2895.000000,2895.000000
mean,2020-10-05 13:10:52.849740800,1901.027010,1901.027010,1911.468671,1890.343904,1900.922833,5065.161658
min,2015-01-02 00:00:00,1050.800049,1050.800049,1062.000000,1046.199951,1053.699951,0.000000
25%,2017-11-16 12:00:00,1275.800049,1275.800049,1281.149963,1272.000000,1276.649963,53.000000
50%,2020-10-06 00:00:00,1732.000000,1732.000000,1741.699951,1722.800049,1732.400024,211.000000
75%,2023-08-22 12:00:00,1977.900024,1977.900024,1983.950012,1968.400024,1976.750000,652.000000
max,2026-07-10 00:00:00,5318.399902,5318.399902,5586.200195,5301.600098,5415.700195,386334.000000
std,NaN,886.239123,886.239123,895.124922,877.396139,886.894275,27758.237093

In [21]:
gold.loc[gold["Close"].idxmax()]

Date         2026-01-29 00:00:00
Adj Close            5318.399902
Close                5318.399902
High                 5586.200195
Low                       5097.5
Open                 5415.700195
Volume                     23709
Name: 2783, dtype: object

In [22]:
gold[gold["Volume"] == 0].head()

,Date,Adj Close,Close,High,Low,Open,Volume
728,2017-11-24,1286.699951,1286.699951,1286.699951,1286.699951,1286.699951,0
799,2018-03-12,1319.400024,1319.400024,1319.400024,1319.400024,1319.400024,0
802,2018-03-15,1316.800049,1316.800049,1316.800049,1316.800049,1316.800049,0
807,2018-03-22,1326.599976,1326.599976,1326.599976,1326.599976,1326.599976,0
837,2018-05-04,1312.699951,1312.699951,1312.699951,1312.699951,1312.699951,0

In [17]:
(gold["High"] >= gold["Low"]).all()

np.True_

In [19]:
gold["Volume"].describe()

count      2895.000000
mean       5065.161658
std       27758.237093
min           0.000000
25%          53.000000
50%         211.000000
75%         652.000000
max      386334.000000
Name: Volume, dtype: float64

In [26]:
import sys
from pathlib import Path

sys.path.append(str(Path("../utils").resolve()))

from validation import validate_dataset

In [29]:
gold_summary = validate_dataset(gold, "Gold")
silver_summary = validate_dataset(silver, "Silver")
oil_summary = validate_dataset(crude_oil, "Crude Oil")
gas_summary = validate_dataset(natural_gas, "Natural Gas")
copper_summary = validate_dataset(copper, "Copper")

======================================================================
DATA VALIDATION REPORT : Gold
======================================================================
Shape                : (2895, 7)
Date Range           : 2015-01-02 → 2026-07-10
Missing Values       : 0
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 37
Minimum Close Price  : 1050.80
Maximum Close Price  : 5318.40
Average Close Price  : 1901.03

Data Types
Date          object
Adj Close    float64
Close        float64
High         float64
Low          float64
Open         float64
Volume         int64
dtype: object

Missing Values by Column
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
         Adj Close        Close         High          Low         Open  \
count  2895.000000  2895.000000  2895.000000  2895.000000  2895.000000
mean   1901.027010  1901.027010  1911.468671  1890.343904  1900.922833
std     886.239123   886.239123   895.124922   877.396139   886.894275
min    1050.800049  1050.800049  1062.000000  1046.199951  1053.699951
25%    1275.800049  1275.800049  1281.149963  1272.000000  1276.649963
50%    1732.000000  1732.000000  1741.699951  1722.800049  1732.400024
75%    1977.900024  1977.900024  1983.950012  1968.400024  1976.750000
max    5318.399902  5318.399902  5586.200195  5301.600098  5415.700195

              Volume
count    2895.000000
mean     5065.161658
std     27758.237093
min         0.000000
25%        53.000000
50%       211.000000
75%       652.000000
max    386334.000000
======================================================================
======================================================================
DATA VALIDATION REPORT : Silver
======================================================================
Shape                : (2895, 7)
Date Range           : 2015-01-02 → 2026-07-10
Missing Values       : 0
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 188
Minimum Close Price  : 11.73
Maximum Close Price  : 115.08
Average Close Price  : 24.40

Data Types
Date          object
Adj Close    float64
Close        float64
High         float64
Low          float64
Open         float64
Volume         int64
dtype: object

Missing Values by Column
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
         Adj Close        Close         High          Low         Open  \
count  2895.000000  2895.000000  2895.000000  2895.000000  2895.000000
mean     24.402144    24.402144    24.633889    24.189071    24.420023
std      14.026925    14.026925    14.421115    13.695457    14.091488
min      11.735000    11.735000    12.205000    11.735000    12.070000
25%      16.486500    16.486500    16.555000    16.411000    16.492500
50%      20.004999    20.004999    20.105000    19.848000    19.985001
75%      25.793000    25.793000    25.967500    25.534500    25.816501
max     115.080002   115.080002   121.300003   112.735001   116.889999

              Volume
count    2895.000000
mean     1725.056304
std      9797.965177
min         0.000000
25%        10.000000
50%        48.000000
75%       178.000000
max    131415.000000
======================================================================
======================================================================
DATA VALIDATION REPORT : Crude Oil
======================================================================
Shape                : (2896, 7)
Date Range           : 2015-01-02 → 2026-07-10
Missing Values       : 0
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 7
Minimum Close Price  : -37.63
Maximum Close Price  : 123.70
Average Close Price  : 63.14

Data Types
Date          object
Adj Close    float64
Close        float64
High         float64
Low          float64
Open         float64
Volume         int64
dtype: object

Missing Values by Column
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
         Adj Close        Close         High          Low         Open  \
count  2896.000000  2896.000000  2896.000000  2896.000000  2896.000000
mean     63.142086    63.142086    64.305525    61.982731    63.188101
std      17.796241    17.796241    18.115468    17.441992    17.783412
min     -37.630001   -37.630001    13.690000   -40.320000   -14.000000
25%      49.937499    49.937499    50.817500    49.197500    49.937499
50%      61.970001    61.970001    62.940001    61.085001    61.955000
75%      73.942501    73.942501    75.250000    72.832500    74.064999
max     123.699997   123.699997   130.500000   120.790001   124.660004

             Volume
count  2.896000e+03
mean   4.398173e+05
std    2.158006e+05
min    0.000000e+00
25%    2.925465e+05
50%    3.941665e+05
75%    5.744860e+05
max    2.288230e+06
======================================================================
======================================================================
DATA VALIDATION REPORT : Natural Gas
======================================================================
Shape                : (2897, 7)
Date Range           : 2015-01-02 → 2026-07-10
Missing Values       : 0
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 7
Minimum Close Price  : 1.48
Maximum Close Price  : 9.68
Average Close Price  : 3.17

Data Types
Date          object
Adj Close    float64
Close        float64
High         float64
Low          float64
Open         float64
Volume         int64
dtype: object

Missing Values by Column
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
         Adj Close        Close         High          Low         Open  \
count  2897.000000  2897.000000  2897.000000  2897.000000  2897.000000
mean      3.171322     3.171322     3.260101     3.089259     3.174245
std       1.328922     1.328922     1.391424     1.267048     1.327357
min       1.482000     1.482000     1.567000     1.432000     1.441000
25%       2.510000     2.510000     2.568000     2.451000     2.506000
50%       2.837000     2.837000     2.891000     2.784000     2.835000
75%       3.279000     3.279000     3.369000     3.210000     3.293000
max       9.680000     9.680000    10.028000     9.200000     9.817000

              Volume
count    2897.000000
mean   147883.456334
std     58738.123582
min         0.000000
25%    110913.000000
50%    144669.000000
75%    179726.000000
max    554857.000000
======================================================================
======================================================================
DATA VALIDATION REPORT : Copper
======================================================================
Shape                : (2896, 7)
Date Range           : 2015-01-02 → 2026-07-10
Missing Values       : 0
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 7
Minimum Close Price  : 1.94
Maximum Close Price  : 6.65
Average Close Price  : 3.49

Data Types
Date          object
Adj Close    float64
Close        float64
High         float64
Low          float64
Open         float64
Volume         int64
dtype: object

Missing Values by Column
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
         Adj Close        Close         High          Low         Open  \
count  2896.000000  2896.000000  2896.000000  2896.000000  2896.000000
mean      3.491459     3.491459     3.514461     3.465168     3.490021
std       1.019296     1.019296     1.027661     1.008457     1.017748
min       1.939500     1.939500     1.962500     1.936500     1.936500
25%       2.658375     2.658375     2.673375     2.642000     2.657000
50%       3.199000     3.199000     3.213250     3.182500     3.199000
75%       4.263500     4.263500     4.293875     4.231500     4.265875
max       6.649500     6.649500     6.652500     6.634000     6.652500

             Volume
count   2896.000000
mean    1650.984461
std     6263.871391
min        0.000000
25%      369.000000
50%      536.500000
75%      816.000000
max    79408.000000
======================================================================

In [31]:
silver["Date"]=pd.to_datetime(gold["Date"])
natural_gas["Date"]=pd.to_datetime(gold["Date"])
crude_oil["Date"]=pd.to_datetime(gold["Date"])
copper["Date"]=pd.to_datetime(gold["Date"])

In [32]:
summaries = []

summaries.append(validate_dataset(gold, "Gold"))
summaries.append(validate_dataset(silver, "Silver"))
summaries.append(validate_dataset(crude_oil, "Crude Oil"))
summaries.append(validate_dataset(natural_gas, "Natural Gas"))
summaries.append(validate_dataset(copper, "Copper"))

quality_report = pd.DataFrame(summaries)
quality_report

======================================================================
DATA VALIDATION REPORT : Gold
======================================================================
Shape                : (2895, 7)
Date Range           : 2015-01-02 00:00:00 → 2026-07-10 00:00:00
Missing Values       : 0
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 37
Minimum Close Price  : 1050.80
Maximum Close Price  : 5318.40
Average Close Price  : 1901.03

Data Types
Date         datetime64[ns]
Adj Close           float64
Close               float64
High                float64
Low                 float64
Open                float64
Volume                int64
dtype: object

Missing Values by Column
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
                                Date    Adj Close        Close         High  \
count                           2895  2895.000000  2895.000000  2895.000000
mean   2020-10-05 13:10:52.849740800  1901.027010  1901.027010  1911.468671
min              2015-01-02 00:00:00  1050.800049  1050.800049  1062.000000
25%              2017-11-16 12:00:00  1275.800049  1275.800049  1281.149963
50%              2020-10-06 00:00:00  1732.000000  1732.000000  1741.699951
75%              2023-08-22 12:00:00  1977.900024  1977.900024  1983.950012
max              2026-07-10 00:00:00  5318.399902  5318.399902  5586.200195
std                              NaN   886.239123   886.239123   895.124922

               Low         Open         Volume
count  2895.000000  2895.000000    2895.000000
mean   1890.343904  1900.922833    5065.161658
min    1046.199951  1053.699951       0.000000
25%    1272.000000  1276.649963      53.000000
50%    1722.800049  1732.400024     211.000000
75%    1968.400024  1976.750000     652.000000
max    5301.600098  5415.700195  386334.000000
std     877.396139   886.894275   27758.237093
======================================================================
======================================================================
DATA VALIDATION REPORT : Silver
======================================================================
Shape                : (2895, 7)
Date Range           : 2015-01-02 00:00:00 → 2026-07-10 00:00:00
Missing Values       : 0
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 188
Minimum Close Price  : 11.73
Maximum Close Price  : 115.08
Average Close Price  : 24.40

Data Types
Date         datetime64[ns]
Adj Close           float64
Close               float64
High                float64
Low                 float64
Open                float64
Volume                int64
dtype: object

Missing Values by Column
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
                                Date    Adj Close        Close         High  \
count                           2895  2895.000000  2895.000000  2895.000000
mean   2020-10-05 13:10:52.849740800    24.402144    24.402144    24.633889
min              2015-01-02 00:00:00    11.735000    11.735000    12.205000
25%              2017-11-16 12:00:00    16.486500    16.486500    16.555000
50%              2020-10-06 00:00:00    20.004999    20.004999    20.105000
75%              2023-08-22 12:00:00    25.793000    25.793000    25.967500
max              2026-07-10 00:00:00   115.080002   115.080002   121.300003
std                              NaN    14.026925    14.026925    14.421115

               Low         Open         Volume
count  2895.000000  2895.000000    2895.000000
mean     24.189071    24.420023    1725.056304
min      11.735000    12.070000       0.000000
25%      16.411000    16.492500      10.000000
50%      19.848000    19.985001      48.000000
75%      25.534500    25.816501     178.000000
max     112.735001   116.889999  131415.000000
std      13.695457    14.091488    9797.965177
======================================================================
======================================================================
DATA VALIDATION REPORT : Crude Oil
======================================================================
Shape                : (2896, 7)
Date Range           : 2015-01-02 00:00:00 → 2026-07-10 00:00:00
Missing Values       : 1
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 7
Minimum Close Price  : -37.63
Maximum Close Price  : 123.70
Average Close Price  : 63.14

Data Types
Date         datetime64[ns]
Adj Close           float64
Close               float64
High                float64
Low                 float64
Open                float64
Volume                int64
dtype: object

Missing Values by Column
Date         1
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
                                Date    Adj Close        Close         High  \
count                           2895  2896.000000  2896.000000  2896.000000
mean   2020-10-05 13:10:52.849741056    63.142086    63.142086    64.305525
min              2015-01-02 00:00:00   -37.630001   -37.630001    13.690000
25%              2017-11-16 12:00:00    49.937499    49.937499    50.817500
50%              2020-10-06 00:00:00    61.970001    61.970001    62.940001
75%              2023-08-22 12:00:00    73.942501    73.942501    75.250000
max              2026-07-10 00:00:00   123.699997   123.699997   130.500000
std                              NaN    17.796241    17.796241    18.115468

               Low         Open        Volume
count  2896.000000  2896.000000  2.896000e+03
mean     61.982731    63.188101  4.398173e+05
min     -40.320000   -14.000000  0.000000e+00
25%      49.197500    49.937499  2.925465e+05
50%      61.085001    61.955000  3.941665e+05
75%      72.832500    74.064999  5.744860e+05
max     120.790001   124.660004  2.288230e+06
std      17.441992    17.783412  2.158006e+05
======================================================================
======================================================================
DATA VALIDATION REPORT : Natural Gas
======================================================================
Shape                : (2897, 7)
Date Range           : 2015-01-02 00:00:00 → 2026-07-10 00:00:00
Missing Values       : 2
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 7
Minimum Close Price  : 1.48
Maximum Close Price  : 9.68
Average Close Price  : 3.17

Data Types
Date         datetime64[ns]
Adj Close           float64
Close               float64
High                float64
Low                 float64
Open                float64
Volume                int64
dtype: object

Missing Values by Column
Date         2
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
                                Date    Adj Close        Close         High  \
count                           2895  2897.000000  2897.000000  2897.000000
mean   2020-10-05 13:10:52.849741056     3.171322     3.171322     3.260101
min              2015-01-02 00:00:00     1.482000     1.482000     1.567000
25%              2017-11-16 12:00:00     2.510000     2.510000     2.568000
50%              2020-10-06 00:00:00     2.837000     2.837000     2.891000
75%              2023-08-22 12:00:00     3.279000     3.279000     3.369000
max              2026-07-10 00:00:00     9.680000     9.680000    10.028000
std                              NaN     1.328922     1.328922     1.391424

               Low         Open         Volume
count  2897.000000  2897.000000    2897.000000
mean      3.089259     3.174245  147883.456334
min       1.432000     1.441000       0.000000
25%       2.451000     2.506000  110913.000000
50%       2.784000     2.835000  144669.000000
75%       3.210000     3.293000  179726.000000
max       9.200000     9.817000  554857.000000
std       1.267048     1.327357   58738.123582
======================================================================
======================================================================
DATA VALIDATION REPORT : Copper
======================================================================
Shape                : (2896, 7)
Date Range           : 2015-01-02 00:00:00 → 2026-07-10 00:00:00
Missing Values       : 1
Duplicate Rows       : 0
High >= Low          : True
Zero Volume Days     : 7
Minimum Close Price  : 1.94
Maximum Close Price  : 6.65
Average Close Price  : 3.49

Data Types
Date         datetime64[ns]
Adj Close           float64
Close               float64
High                float64
Low                 float64
Open                float64
Volume                int64
dtype: object

Missing Values by Column
Date         1
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Summary Statistics
                                Date    Adj Close        Close         High  \
count                           2895  2896.000000  2896.000000  2896.000000
mean   2020-10-05 13:10:52.849741056     3.491459     3.491459     3.514461
min              2015-01-02 00:00:00     1.939500     1.939500     1.962500
25%              2017-11-16 12:00:00     2.658375     2.658375     2.673375
50%              2020-10-06 00:00:00     3.199000     3.199000     3.213250
75%              2023-08-22 12:00:00     4.263500     4.263500     4.293875
max              2026-07-10 00:00:00     6.649500     6.649500     6.652500
std                              NaN     1.019296     1.019296     1.027661

               Low         Open        Volume
count  2896.000000  2896.000000   2896.000000
mean      3.465168     3.490021   1650.984461
min       1.936500     1.936500      0.000000
25%       2.642000     2.657000    369.000000
50%       3.182500     3.199000    536.500000
75%       4.231500     4.265875    816.000000
max       6.634000     6.652500  79408.000000
std       1.008457     1.017748   6263.871391
======================================================================

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Start Date,End Date,High >= Low,Zero Volume Days,Maximum Close,Minimum Close,Average Close
0,Gold,2895,7,0,0,2015-01-02,2026-07-10,True,37,5318.399902,1050.800049,1901.03
1,Silver,2895,7,0,0,2015-01-02,2026-07-10,True,188,115.080002,11.735000,24.40
2,Crude Oil,2896,7,1,0,2015-01-02,2026-07-10,True,7,123.699997,-37.630001,63.14
3,Natural Gas,2897,7,2,0,2015-01-02,2026-07-10,True,7,9.680000,1.482000,3.17
4,Copper,2896,7,1,0,2015-01-02,2026-07-10,True,7,6.649500,1.939500,3.49